### ISSUE TITLE
Call to Toni Dialogue lags

### ISSUE THREAD

**Issue by martinsillaots** [centre-for-educational-technology/Melange#9]
Call from the lunch table to Toni lags. All options to the player appear after 15 - 30 sec waiting.

**Comment by sanderaido** [comment]
This error one took a while to find, it was caused by the actual sound files not being cut to the correct length (a lot of silence at the end of sound files and the script waited for the sound file to finish). 
This was only on Toni's files in that one dialogue and affected about 10 nodes, so I cut the sound files to proper length myself (will update in Dropbox source files as well).

**Comment by martinsillaots** [comment]
Following Toni's sentences have still remarkable lag:
- Hola Susi! …
- Hey Mali …
- Susi, Hola
- Qui est? Papa
- I live in Barcelona now. …
- I can’t wait to see you …

**Comment by sanderaido** [comment]
Tested and fixed, also in a few dialogues in Zeil
